export const events = [
  {
    id: 'ev-01',
    title: 'Staff para matrimonio elegante',
    pay: 'S/. 260 por turno',
    location: 'Lima - Miraflores',
    date: '2024-12-02',
    type: 'Matrimonio',
    timeRange: '4:00 pm - 11:30 pm',
    staffNeeded: 10,
    description: 'Apoyo en recepción, orientación de invitados y control de brindis en matrimonio estilo moderno.',
    requirements: ['Vestimenta negra formal', 'Experiencia mínima en eventos sociales', 'Actitud cordial y proactiva'],
    contactInfo: 'WhatsApp: +51 987 654 321'
  },
  {
    id: 'ev-02',
    title: 'Coordinador de registro en festival urbano',
    pay: 'S/. 230 por turno',
    location: 'Lima - Barranco',
    date: '2024-12-05',
    type: 'Conciertos / Festivales',
    timeRange: '2:00 pm - 10:00 pm',
    staffNeeded: 6,
    description: 'Chequear accesos, validar boletos digitales y orientar al público joven en festival de música urbana.',
    requirements: ['Conocer apps de tickets', 'Facilidad de palabra', 'Disponibilidad para briefing previo'],
    contactInfo: 'Tel: 01 456 7890'
  },
  {
    id: 'ev-03',
    title: 'Barback para evento mixología premium',
    pay: 'S/. 280 + propinas',
    location: 'Lima - San Isidro',
    date: '2024-12-08',
    type: 'Staff para discotecas / bares',
    timeRange: '5:00 pm - 1:00 am',
    staffNeeded: 4,
    description: 'Soporte a bartenders, reposición de barra y limpieza rápida en barra de hotel.',
    requirements: ['Experiencia en barback', 'Conocer cristalería básica', 'Calzado negro antideslizante'],
    contactInfo: 'WhatsApp: +51 999 222 333'
  },
  {
    id: 'ev-04',
    title: 'Host digital en activación fintech',
    pay: 'S/. 240 por turno',
    location: 'Lima - San Borja',
    date: '2024-12-10',
    type: 'Activaciones de marca',
    timeRange: '3:00 pm - 9:30 pm',
    staffNeeded: 3,
    description: 'Recibir invitados VIP, coordinar check-in con tablets y guiar a la zona demo.',
    requirements: ['Manejo de tablets', 'Comunicación asertiva', 'Look business casual'],
    contactInfo: 'Correo: talento@fintech.pe'
  },
  {
    id: 'ev-05',
    title: 'Animador para quinceañero neon',
    pay: 'S/. 210 por turno',
    location: 'Lima - La Molina',
    date: '2024-12-12',
    type: 'Quinceañeros',
    timeRange: '6:00 pm - 12:30 am',
    staffNeeded: 2,
    description: 'Micro dinámicas en pista, rompehielos y anuncios rápidos durante la fiesta.',
    requirements: ['Alta energía', 'Experiencia animando grupos', 'Sin miedo al micrófono'],
    contactInfo: 'Tel: 01 222 3344'
  },
  {
    id: 'ev-06',
    title: 'Runner en concierto indie',
    pay: 'S/. 230 por turno',
    location: 'Arequipa - Cercado',
    date: '2024-12-13',
    type: 'Conciertos / Festivales',
    timeRange: '1:00 pm - 10:30 pm',
    staffNeeded: 5,
    description: 'Apoyo en camerinos, traslado de snacks y coordinación rápida entre producción y talento.',
    requirements: ['Buen estado físico', 'Atención al detalle', 'Conocer rutas cortas en el venue'],
    contactInfo: 'WhatsApp: +51 944 111 222'
  },
  {
    id: 'ev-07',
    title: 'Meseros para brunch corporativo',
    pay: 'S/. 190 + propinas',
    location: 'Lima - San Isidro',
    date: '2024-12-14',
    type: 'Eventos corporativos',
    timeRange: '7:00 am - 1:00 pm',
    staffNeeded: 12,
    description: 'Servicio de mesas, café y pastelería en brunch ejecutivo minimalista.',
    requirements: ['Servicio a la mesa', 'Look formal discreto', 'Disponibilidad para capacitación previa'],
    contactInfo: 'Correo: hr@corporativo.pe'
  },
  {
    id: 'ev-08',
    title: 'Brand ambassador bebida energizante',
    pay: 'S/. 250 por turno',
    location: 'Callao - La Perla',
    date: '2024-12-16',
    type: 'Activaciones de marca',
    timeRange: '10:00 am - 6:00 pm',
    staffNeeded: 8,
    description: 'Activación en campus, sampling y mini retos con estudiantes en puntos calientes.',
    requirements: ['Carisma alto', 'Conocer tendencias de TikTok', 'Buen manejo de público'],
    contactInfo: 'WhatsApp: +51 933 555 777'
  },
  {
    id: 'ev-09',
    title: 'Recepción en gala de moda limeña',
    pay: 'S/. 270 por turno',
    location: 'Lima - San Isidro',
    date: '2024-12-18',
    type: 'Eventos corporativos',
    timeRange: '4:30 pm - 11:00 pm',
    staffNeeded: 6,
    description: 'Guiding seating, atención a prensa y acompañamiento en photocall local.',
    requirements: ['Etiqueta urbana chic', 'Trato con prensa', 'Proactividad'],
    contactInfo: 'Correo: moda@glow.pe'
  },
  {
    id: 'ev-10',
    title: 'Logística en noche k-pop',
    pay: 'S/. 220 por turno',
    location: 'Lima - Surco',
    date: '2024-12-20',
    type: 'Conciertos / Festivales',
    timeRange: '3:00 pm - 11:00 pm',
    staffNeeded: 14,
    description: 'Control de accesos, apoyo en merch y coordinación de fila para hi-touch.',
    requirements: ['Orden y paciencia', 'Fan friendly', 'Capacidad para hablar en público'],
    contactInfo: 'WhatsApp: +51 900 456 789'
  },
  {
    id: 'ev-11',
    title: 'Caddie para torneo nocturno',
    pay: 'S/. 320 por turno',
    location: 'Lima - La Molina',
    date: '2024-12-22',
    type: 'Eventos corporativos',
    timeRange: '5:00 pm - 12:00 am',
    staffNeeded: 6,
    description: 'Apoyo a jugadores, carga ligera y orientación en campo iluminado.',
    requirements: ['Resistencia física', 'Conocimiento básico de golf', 'Disponibilidad para brieffing'],
    contactInfo: 'Tel: 01 567 8899'
  },
  {
    id: 'ev-12',
    title: 'Hostess lounge VIP festival electrónico',
    pay: 'S/. 300 por turno',
    location: 'Lima - Costa Verde',
    date: '2024-12-23',
    type: 'Conciertos / Festivales',
    timeRange: '2:00 pm - 11:00 pm',
    staffNeeded: 5,
    description: 'Atención en lounge premium, wristbands y acompañamiento en zonas restringidas.',
    requirements: ['Inglés intermedio', 'Trato premium', 'Look black smart'],
    contactInfo: 'Correo: vip@festival.pe'
  },
  {
    id: 'ev-13',
    title: 'Staff en feria gastronómica',
    pay: 'S/. 180 por turno',
    location: 'Lima - Magdalena',
    date: '2024-12-27',
    type: 'Eventos corporativos',
    timeRange: '9:00 am - 5:00 pm',
    staffNeeded: 15,
    description: 'Soporte en stands, degustaciones y flujo de visitantes foodie.',
    requirements: ['Gusto por gastronomía', 'Atención al cliente', 'Manejo de POS básico'],
    contactInfo: 'WhatsApp: +51 955 666 777'
  },
  {
    id: 'ev-14',
    title: 'Auxiliar de producción videoclip',
    pay: 'S/. 240 por turno',
    location: 'Lima - Chorrillos',
    date: '2024-12-28',
    type: 'Producción / Backstage',
    timeRange: '8:00 am - 5:00 pm',
    staffNeeded: 7,
    description: 'Montaje ligero, audio básico y cuidado de props en grabación urbana.',
    requirements: ['Mover equipos', 'Puntualidad extrema', 'Conocer básicos de audio'],
    contactInfo: 'Correo: produccion@clips.pe'
  },
  {
    id: 'ev-15',
    title: 'Runner para conversatorio gaming',
    pay: 'S/. 200 por turno',
    location: 'Lima - Miraflores',
    date: '2024-12-29',
    type: 'Eventos corporativos',
    timeRange: '10:00 am - 6:00 pm',
    staffNeeded: 4,
    description: 'Apoyo backstage, micrófonos y acompañar a speakers gamer.',
    requirements: ['Afinidad gaming', 'Saber armar micrófonos de solapa', 'Respetar agenda'],
    contactInfo: 'WhatsApp: +51 902 001 889'
  },
  {
    id: 'ev-16',
    title: 'Barista en pop-up navideño',
    pay: 'S/. 210 + propinas',
    location: 'Lima - San Miguel',
    date: '2024-12-30',
    type: 'Staff para discotecas / bares',
    timeRange: '8:00 am - 4:00 pm',
    staffNeeded: 3,
    description: 'Preparar bebidas sencillas, latte art básico y manejo de POS en módulo temporal.',
    requirements: ['Experiencia barista', 'Trato amable', 'Higiene y cuidado de barra'],
    contactInfo: 'Correo: cafe@pop.pe'
  },
  {
    id: 'ev-17',
    title: 'Guía de sala en expo de arte',
    pay: 'S/. 170 por turno',
    location: 'Lima - Barranco',
    date: '2024-12-30',
    type: 'Activaciones de marca',
    timeRange: '11:00 am - 7:00 pm',
    staffNeeded: 6,
    description: 'Orientar a visitantes, cuidar obra y narrativas rápidas de artistas peruanos.',
    requirements: ['Interés por arte', 'Trato pausado y cordial', 'Disponibilidad completa'],
    contactInfo: 'WhatsApp: +51 933 222 444'
  },
  {
    id: 'ev-18',
    title: 'Staff meetup makers',
    pay: 'S/. 190 por turno',
    location: 'Lima - Jesús María',
    date: '2025-01-03',
    type: 'Eventos corporativos',
    timeRange: '8:00 am - 3:00 pm',
    staffNeeded: 5,
    description: 'Check-in, coffee station y dinámicas ice-breaker para comunidad tech local.',
    requirements: ['Saber usar lector QR', 'Actitud de servicio', 'Comunicación clara'],
    contactInfo: 'Tel: 01 555 0101'
  },
  {
    id: 'ev-19',
    title: 'Asistente en torneo e-sports',
    pay: 'S/. 240 por turno',
    location: 'Lima - Los Olivos',
    date: '2025-01-05',
    type: 'Eventos corporativos',
    timeRange: '9:00 am - 6:00 pm',
    staffNeeded: 9,
    description: 'Control de brackets, hospitality y apoyo a casters en LAN center.',
    requirements: ['Conocer juegos MOBA/FPS', 'Manejo básico de OBS', 'Trabajo en equipo'],
    contactInfo: 'WhatsApp: +51 922 333 444'
  },
  {
    id: 'ev-20',
    title: 'Staff pista de patinaje pop-up',
    pay: 'S/. 185 por turno',
    location: 'Arequipa - Cayma',
    date: '2025-01-07',
    type: 'Producción / Backstage',
    timeRange: '10:00 am - 8:00 pm',
    staffNeeded: 6,
    description: 'Préstamo de equipo, tips rápidos y seguridad en pista temporal.',
    requirements: ['Saber patinar básico', 'Primeros auxilios básicos', 'Atención a familias'],
    contactInfo: 'Correo: eventos@andina.pe'
  }
];
